unit tests written
turingsquad/FakedPeopleBot pull request #6
Opened 2019-11-11 18:15 UTC by ilyashn

2019-11-11 18:19 UTC, Arthasasyan commented
@ilyashn please, write [`.travis.yml`](https://docs.travis-ci.com/user/languages/python) file

2019-11-11 18:19 UTC, Arthasasyan commented
Note that bot does not require to work on python under 3.5

2019-11-11 18:23 UTC, Arthasasyan commented
Please, add new lines at the end of all files

2019-11-11 18:25 UTC, Arthasasyan requested changes

2019-11-11 18:25 UTC, Arthasasyan commented on config/config.ini
> +token = NjQzMTAyMDc5MzkyNjc3ODk4.XclMlA.wDkz8rZHXMcy-MNwsuWJw38v7wU
Don't write bot token publically

2019-11-11 19:19 UTC, merged

2019-11-12 08:22 UTC, ilyashn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Настройка конфига для Travis CI](https://trello.com/c/OeLjwC5b/20-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%B4%D0%BB%D1%8F-travis-ci)